server:
  port: 83
spring:
  application:
    name: nacos-customer-payment
  cloud:
    nacos:
      discovery:
        server-addr: 47.97.178.43:1111
#消费者要去访问的微服务的名称（注册成功进nacos的微服务提供者）
service-url:
  nacos-user-service: http://nacos-provider-payment
