server:
  port: 9004

spring:
  application:
    name: cloudalibaba-provider-payment
  cloud:
    nacos:
      discovery:
        server-addr: 47.97.178.43:1111

management:
  endpoints:
    web:
      exposure:
        include: '*'
