server:
  port: 9002

spring:
  application:
    name: nacos-provider-payment
  cloud:
    nacos:
      discovery:
        server-addr: 47.97.178.43:1111
management:
  endpoints:
    web:
      exposure:
        include: '*'
