server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db2020?useSSL=false&userUnicode=true&charsetEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.zengjie.entities

eureka:
  client:
    #是否将自己注册进eureka
    register-with-eureka: true
    #是否从eurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7002/eureka/,http://localhost:7001/eureka
  instance:
    #修改eureka的名字
    instance-id: payment8001
    #显示ip地址
    prefer-ip-address: true
    #Eureka客户端向服务器发送心跳的时间间隔，单位为秒（默认是30s）
    lease-renewal-interval-in-seconds: 1
    #Eureka服务端在收到最后一次心跳后等待时间上限，单位为秒（默认是90s），超时将剔除服务
    lease-expiration-duration-in-seconds: 2