server:
  port: 8001

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka
    register-with-eureka: true
    fetch-registry: true

spring:
  application:
    name: cloud-provider-hystrix-payment