server:
  port: 84

spring:
  application:
    name: cloudalibaba-nacos-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 47.97.178.43:1111

management:
  endpoints:
    web:
      exposure:
        include: '*'
